//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

//[assembly: PureLiveAssembly]
//[assembly: ModelsBuilderAssembly(PureLive = true, SourceHash = "a0ae3aa83d7f77e9")]
//[assembly: System.Reflection.AssemblyVersion("0.0.0.2")]

namespace Umbraco.Web.PublishedModels
{
    /// <summary>Home</summary>
    [PublishedModel("home")]
    public partial class Home : PublishedContentModel, IBanner, IBaseDocType, ITitleAndContent, IVideoRendering
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "home";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public Home(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Services
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("services")]
        public IEnumerable<IPublishedElement> Services => this.Value<IEnumerable<IPublishedElement>>("services");

        ///<summary>
        /// CTA
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerCTA")]
        public IEnumerable<Umbraco.Web.Models.Link> BannerCta => Banner.GetBannerCta(this);

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerHeading")]
        public string BannerHeading => Banner.GetBannerHeading(this);

        ///<summary>
        /// Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerImage")]
        public IPublishedContent BannerImage => Banner.GetBannerImage(this);

        ///<summary>
        /// Page Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageDescription")]
        public string PageDescription => BaseDocType.GetPageDescription(this);

        ///<summary>
        /// Page Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageTitle")]
        public string PageTitle => BaseDocType.GetPageTitle(this);

        ///<summary>
        /// Content
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("tcContent")]
        public string TcContent => TitleAndContent.GetTcContent(this);

        ///<summary>
        /// Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("tcTitle")]
        public string TcTitle => TitleAndContent.GetTcTitle(this);

        ///<summary>
        /// Cover Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vCoverImage")]
        public IPublishedContent VCoverImage => VideoRendering.GetVCoverImage(this);

        ///<summary>
        /// Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vDescription")]
        public string VDescription => VideoRendering.GetVDescription(this);

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vHeading")]
        public string VHeading => VideoRendering.GetVHeading(this);

        ///<summary>
        /// Video URL
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vVideoURL")]
        public IEnumerable<Umbraco.Web.Models.Link> VVideoUrl => VideoRendering.GetVVideoUrl(this);
    }

    // Mixin Content Type with alias "baseDocType"
    /// <summary>Base DocType</summary>
    public partial interface IBaseDocType : IPublishedContent
    {
        /// <summary>Page Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string PageDescription { get; }

        /// <summary>Page Title</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string PageTitle { get; }
    }

    /// <summary>Base DocType</summary>
    [PublishedModel("baseDocType")]
    public partial class BaseDocType : PublishedContentModel, IBaseDocType
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "baseDocType";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseDocType, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public BaseDocType(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Page Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageDescription")]
        public string PageDescription => GetPageDescription(this);

        /// <summary>Static getter for Page Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetPageDescription(IBaseDocType that) => that.Value<string>("pageDescription");

        ///<summary>
        /// Page Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageTitle")]
        public string PageTitle => GetPageTitle(this);

        /// <summary>Static getter for Page Title</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetPageTitle(IBaseDocType that) => that.Value<string>("pageTitle");
    }

    // Mixin Content Type with alias "banner"
    /// <summary>Banner</summary>
    public partial interface IBanner : IPublishedContent
    {
        /// <summary>CTA</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        IEnumerable<Umbraco.Web.Models.Link> BannerCta { get; }

        /// <summary>Heading</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string BannerHeading { get; }

        /// <summary>Image</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        IPublishedContent BannerImage { get; }
    }

    /// <summary>Banner</summary>
    [PublishedModel("banner")]
    public partial class Banner : PublishedContentModel, IBanner
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "banner";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Banner, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public Banner(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// CTA
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerCTA")]
        public IEnumerable<Umbraco.Web.Models.Link> BannerCta => GetBannerCta(this);

        /// <summary>Static getter for CTA</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static IEnumerable<Umbraco.Web.Models.Link> GetBannerCta(IBanner that) => that.Value<IEnumerable<Umbraco.Web.Models.Link>>("bannerCTA");

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerHeading")]
        public string BannerHeading => GetBannerHeading(this);

        /// <summary>Static getter for Heading</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetBannerHeading(IBanner that) => that.Value<string>("bannerHeading");

        ///<summary>
        /// Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerImage")]
        public IPublishedContent BannerImage => GetBannerImage(this);

        /// <summary>Static getter for Image</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static IPublishedContent GetBannerImage(IBanner that) => that.Value<IPublishedContent>("bannerImage");
    }

    /// <summary>Generic Page</summary>
    [PublishedModel("genericPage")]
    public partial class GenericPage : PublishedContentModel, IBanner, IBaseDocType
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "genericPage";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenericPage, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public GenericPage(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// CTA
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerCTA")]
        public IEnumerable<Umbraco.Web.Models.Link> BannerCta => Banner.GetBannerCta(this);

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerHeading")]
        public string BannerHeading => Banner.GetBannerHeading(this);

        ///<summary>
        /// Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerImage")]
        public IPublishedContent BannerImage => Banner.GetBannerImage(this);

        ///<summary>
        /// Page Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageDescription")]
        public string PageDescription => BaseDocType.GetPageDescription(this);

        ///<summary>
        /// Page Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageTitle")]
        public string PageTitle => BaseDocType.GetPageTitle(this);
    }

    // Mixin Content Type with alias "titleAndContent"
    /// <summary>Title And Content</summary>
    public partial interface ITitleAndContent : IPublishedContent
    {
        /// <summary>Content</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string TcContent { get; }

        /// <summary>Title</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string TcTitle { get; }
    }

    /// <summary>Title And Content</summary>
    [PublishedModel("titleAndContent")]
    public partial class TitleAndContent : PublishedContentModel, ITitleAndContent
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "titleAndContent";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TitleAndContent, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public TitleAndContent(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Content
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("tcContent")]
        public string TcContent => GetTcContent(this);

        /// <summary>Static getter for Content</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetTcContent(ITitleAndContent that) => that.Value<string>("tcContent");

        ///<summary>
        /// Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("tcTitle")]
        public string TcTitle => GetTcTitle(this);

        /// <summary>Static getter for Title</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetTcTitle(ITitleAndContent that) => that.Value<string>("tcTitle");
    }

    /// <summary>Serquest Folder</summary>
    [PublishedModel("serquestFolder")]
    public partial class SerquestFolder : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "serquestFolder";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SerquestFolder, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public SerquestFolder(IPublishedContent content)
            : base(content)
        { }

        // properties
    }

    /// <summary>Explore Rendering</summary>
    [PublishedModel("exploreRendering")]
    public partial class ExploreRendering : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "exploreRendering";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ExploreRendering, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public ExploreRendering(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Content
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("exploreContent")]
        public IHtmlString ExploreContent => this.Value<IHtmlString>("exploreContent");

        ///<summary>
        /// CTA
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("exploreCTA")]
        public IEnumerable<Umbraco.Web.Models.Link> ExploreCta => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("exploreCTA");

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("exploreHeading")]
        public string ExploreHeading => this.Value<string>("exploreHeading");

        ///<summary>
        /// Icon
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("exploreIcon")]
        public IPublishedContent ExploreIcon => this.Value<IPublishedContent>("exploreIcon");
    }

    /// <summary>Explore Folder</summary>
    [PublishedModel("exploreFolder")]
    public partial class ExploreFolder : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "exploreFolder";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ExploreFolder, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public ExploreFolder(IPublishedContent content)
            : base(content)
        { }

        // properties
    }

    /// <summary>Image And Content</summary>
    [PublishedModel("imageAndContent")]
    public partial class ImageAndContent : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "imageAndContent";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageAndContent, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public ImageAndContent(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Content
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("icContent")]
        public IHtmlString IcContent => this.Value<IHtmlString>("icContent");

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("icHeading")]
        public string IcHeading => this.Value<string>("icHeading");

        ///<summary>
        /// Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("icImage")]
        public IPublishedContent IcImage => this.Value<IPublishedContent>("icImage");
    }

    /// <summary>Image And Content Folder</summary>
    [PublishedModel("imageAndContentFolder")]
    public partial class ImageAndContentFolder : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "imageAndContentFolder";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageAndContentFolder, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public ImageAndContentFolder(IPublishedContent content)
            : base(content)
        { }

        // properties
    }

    /// <summary>Sequest Image And Content</summary>
    [PublishedModel("serImageAndContent")]
    public partial class SerImageAndContent : PublishedElementModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "serImageAndContent";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SerImageAndContent, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public SerImageAndContent(IPublishedElement content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Content
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("serIcContent")]
        public IHtmlString SerIcContent => this.Value<IHtmlString>("serIcContent");

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("serIcHeading")]
        public string SerIcHeading => this.Value<string>("serIcHeading");

        ///<summary>
        /// Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("serIcImage")]
        public IPublishedContent SerIcImage => this.Value<IPublishedContent>("serIcImage");
    }

    /// <summary>Serquest Title And Content</summary>
    [PublishedModel("serTitleAndContent")]
    public partial class SerTitleAndContent : PublishedElementModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "serTitleAndContent";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SerTitleAndContent, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public SerTitleAndContent(IPublishedElement content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Content
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("serTcContent")]
        public string SerTcContent => this.Value<string>("serTcContent");

        ///<summary>
        /// Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("serTcTitle")]
        public string SerTcTitle => this.Value<string>("serTcTitle");
    }

    // Mixin Content Type with alias "videoRendering"
    /// <summary>Video Rendering</summary>
    public partial interface IVideoRendering : IPublishedContent
    {
        /// <summary>Cover Image</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        IPublishedContent VCoverImage { get; }

        /// <summary>Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string VDescription { get; }

        /// <summary>Heading</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string VHeading { get; }

        /// <summary>Video URL</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        IEnumerable<Umbraco.Web.Models.Link> VVideoUrl { get; }
    }

    /// <summary>Video Rendering</summary>
    [PublishedModel("videoRendering")]
    public partial class VideoRendering : PublishedContentModel, IVideoRendering
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "videoRendering";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VideoRendering, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public VideoRendering(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Cover Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vCoverImage")]
        public IPublishedContent VCoverImage => GetVCoverImage(this);

        /// <summary>Static getter for Cover Image</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static IPublishedContent GetVCoverImage(IVideoRendering that) => that.Value<IPublishedContent>("vCoverImage");

        ///<summary>
        /// Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vDescription")]
        public string VDescription => GetVDescription(this);

        /// <summary>Static getter for Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetVDescription(IVideoRendering that) => that.Value<string>("vDescription");

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vHeading")]
        public string VHeading => GetVHeading(this);

        /// <summary>Static getter for Heading</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetVHeading(IVideoRendering that) => that.Value<string>("vHeading");

        ///<summary>
        /// Video URL
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("vVideoURL")]
        public IEnumerable<Umbraco.Web.Models.Link> VVideoUrl => GetVVideoUrl(this);

        /// <summary>Static getter for Video URL</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static IEnumerable<Umbraco.Web.Models.Link> GetVVideoUrl(IVideoRendering that) => that.Value<IEnumerable<Umbraco.Web.Models.Link>>("vVideoURL");
    }

    // Mixin Content Type with alias "blog"
    /// <summary>Blog</summary>
    public partial interface IBlog : IPublishedContent
    {
        /// <summary>Blog Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        IHtmlString BlogDescription { get; }

        /// <summary>Blog Image</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        IPublishedContent BlogImage { get; }

        /// <summary>Blog Short Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string BlogShortDescription { get; }

        /// <summary>Blog Title</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        string BlogTitle { get; }
    }

    /// <summary>Blog</summary>
    [PublishedModel("blog")]
    public partial class Blog : PublishedContentModel, IBlog
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "blog";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Blog, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public Blog(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Blog Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogDescription")]
        public IHtmlString BlogDescription => GetBlogDescription(this);

        /// <summary>Static getter for Blog Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static IHtmlString GetBlogDescription(IBlog that) => that.Value<IHtmlString>("blogDescription");

        ///<summary>
        /// Blog Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogImage")]
        public IPublishedContent BlogImage => GetBlogImage(this);

        /// <summary>Static getter for Blog Image</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static IPublishedContent GetBlogImage(IBlog that) => that.Value<IPublishedContent>("blogImage");

        ///<summary>
        /// Blog Short Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogShortDescription")]
        public string BlogShortDescription => GetBlogShortDescription(this);

        /// <summary>Static getter for Blog Short Description</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetBlogShortDescription(IBlog that) => that.Value<string>("blogShortDescription");

        ///<summary>
        /// Blog Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogTitle")]
        public string BlogTitle => GetBlogTitle(this);

        /// <summary>Static getter for Blog Title</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static string GetBlogTitle(IBlog that) => that.Value<string>("blogTitle");
    }

    /// <summary>Blog Page</summary>
    [PublishedModel("blogPage")]
    public partial class BlogPage : PublishedContentModel, IBanner, IBaseDocType, IBlog
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "blogPage";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogPage, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public BlogPage(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// CTA
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerCTA")]
        public IEnumerable<Umbraco.Web.Models.Link> BannerCta => Banner.GetBannerCta(this);

        ///<summary>
        /// Heading
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerHeading")]
        public string BannerHeading => Banner.GetBannerHeading(this);

        ///<summary>
        /// Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("bannerImage")]
        public IPublishedContent BannerImage => Banner.GetBannerImage(this);

        ///<summary>
        /// Page Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageDescription")]
        public string PageDescription => BaseDocType.GetPageDescription(this);

        ///<summary>
        /// Page Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("pageTitle")]
        public string PageTitle => BaseDocType.GetPageTitle(this);

        ///<summary>
        /// Blog Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogDescription")]
        public IHtmlString BlogDescription => Blog.GetBlogDescription(this);

        ///<summary>
        /// Blog Image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogImage")]
        public IPublishedContent BlogImage => Blog.GetBlogImage(this);

        ///<summary>
        /// Blog Short Description
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogShortDescription")]
        public string BlogShortDescription => Blog.GetBlogShortDescription(this);

        ///<summary>
        /// Blog Title
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("blogTitle")]
        public string BlogTitle => Blog.GetBlogTitle(this);
    }

    /// <summary>Blog Folder</summary>
    [PublishedModel("blogFolder")]
    public partial class BlogFolder : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "blogFolder";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Content;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogFolder, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public BlogFolder(IPublishedContent content)
            : base(content)
        { }

        // properties
    }

    /// <summary>Folder</summary>
    [PublishedModel("Folder")]
    public partial class Folder : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "Folder";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Media;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public Folder(IPublishedContent content)
            : base(content)
        { }

        // properties
    }

    /// <summary>Image</summary>
    [PublishedModel("Image")]
    public partial class Image : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "Image";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Media;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public Image(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Size: in bytes
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoBytes")]
        public long UmbracoBytes => this.Value<long>("umbracoBytes");

        ///<summary>
        /// Type
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoExtension")]
        public string UmbracoExtension => this.Value<string>("umbracoExtension");

        ///<summary>
        /// Upload image
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoFile")]
        public Umbraco.Core.PropertyEditors.ValueConverters.ImageCropperValue UmbracoFile => this.Value<Umbraco.Core.PropertyEditors.ValueConverters.ImageCropperValue>("umbracoFile");

        ///<summary>
        /// Height: in pixels
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoHeight")]
        public int UmbracoHeight => this.Value<int>("umbracoHeight");

        ///<summary>
        /// Width: in pixels
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoWidth")]
        public int UmbracoWidth => this.Value<int>("umbracoWidth");
    }

    /// <summary>File</summary>
    [PublishedModel("File")]
    public partial class File : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "File";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Media;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public File(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Size: in bytes
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoBytes")]
        public long UmbracoBytes => this.Value<long>("umbracoBytes");

        ///<summary>
        /// Type
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoExtension")]
        public string UmbracoExtension => this.Value<string>("umbracoExtension");

        ///<summary>
        /// Upload file
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoFile")]
        public string UmbracoFile => this.Value<string>("umbracoFile");
    }

    /// <summary>Member</summary>
    [PublishedModel("Member")]
    public partial class Member : PublishedContentModel
    {
        // helpers
#pragma warning disable 0109 // new is redundant
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const string ModelTypeAlias = "Member";
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new const PublishedItemType ModelItemType = PublishedItemType.Member;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public new static PublishedContentType GetModelContentType()
            => PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

        // ctor
        public Member(IPublishedContent content)
            : base(content)
        { }

        // properties

        ///<summary>
        /// Is Approved
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberApproved")]
        public bool UmbracoMemberApproved => this.Value<bool>("umbracoMemberApproved");

        ///<summary>
        /// Comments
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberComments")]
        public string UmbracoMemberComments => this.Value<string>("umbracoMemberComments");

        ///<summary>
        /// Failed Password Attempts
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
        public decimal UmbracoMemberFailedPasswordAttempts => this.Value<decimal>("umbracoMemberFailedPasswordAttempts");

        ///<summary>
        /// Last Lockout Date
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberLastLockoutDate")]
        public decimal UmbracoMemberLastLockoutDate => this.Value<decimal>("umbracoMemberLastLockoutDate");

        ///<summary>
        /// Last Login Date
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberLastLogin")]
        public decimal UmbracoMemberLastLogin => this.Value<decimal>("umbracoMemberLastLogin");

        ///<summary>
        /// Last Password Change Date
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
        public decimal UmbracoMemberLastPasswordChangeDate => this.Value<decimal>("umbracoMemberLastPasswordChangeDate");

        ///<summary>
        /// Is Locked Out
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberLockedOut")]
        public bool UmbracoMemberLockedOut => this.Value<bool>("umbracoMemberLockedOut");

        ///<summary>
        /// Password Answer
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
        public decimal UmbracoMemberPasswordRetrievalAnswer => this.Value<decimal>("umbracoMemberPasswordRetrievalAnswer");

        ///<summary>
        /// Password Question
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
        [ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
        public decimal UmbracoMemberPasswordRetrievalQuestion => this.Value<decimal>("umbracoMemberPasswordRetrievalQuestion");
    }

}
